### ISSUE TITLE
Move symfony/symfony variant to separated atribute 

### ISSUE THREAD

**Issue by franmomu** [sonata-project/dev-kit#1502]
Right now we are defining symfony versions as variants:

https://github.com/sonata-project/dev-kit/blob/55060c4a22f6f70278e2924dcbfedf84f80a5f73/config/projects.yaml#L64-L75

The problem with this is that we are installing the complete `symfony/symfony` package which could cause some conflicts.

Instead of doing that, we could maybe move this variant to a `symfony` section, something like:

```yaml
branches:
    master:
        php: ['7.3', '7.4', '8.0']
        symfony: ['4.4', '5.2']
        variants:
            sonata-project/block-bundle: ['4']
    3.x:
        php: ['7.3', '7.4', '8.0']
        symfony: ['4.4', '5.2']
        variants:
            sonata-project/block-bundle: ['3']
```
This way we could add them later as the documentation says: https://symfony.com/doc/4.4/bundles/best_practices.html#require-a-specific-symfony-version
