### ISSUE TITLE
Configure external tools

### ISSUE THREAD

**Issue by core23** [sonata-project/dev-kit#505]
We should add some external tools to the config that are needed for the build pipeline (e.g. phpunit, phpstan, php-cs-fixer, ...), so we can use the [composer-bin plugin](https://github.com/sonata-project/dev-kit/issues/372).

Here is an example config:
```yaml
block-bundle:
  branches:
    master:
      php: ['7.3']
      tools:
          - phpstan
          - phpunit
      versions:
        symfony: ['4.3']
```

This will add new entries to `.travis.yml` and `Makefile`.

We need this for this PR: https://github.com/sonata-project/SonataBlockBundle/pull/611
