### ISSUE TITLE
[RFC] Rename `versions` into `variants`

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#877]
in `projects.yaml`

```yaml
admin-search-bundle:
  branches:
    master:
      php: ['7.2', '7.3', '7.4']
      versions:
        symfony: ['4.4']
        sonata_admin: ['3']
        ruflin_elastica: ['5', '6']
    1.x:
      php: ['7.2', '7.3', '7.4']
      versions:
        symfony: ['4.4']
        sonata_admin: ['3']
        ruflin_elastica: ['5', '6']
```

IMO this is more meaningful
