### ISSUE TITLE
[RFC] Remove mapping and use vendor names directly

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/dev-kit#880]
We have the following mapping:
https://github.com/sonata-project/dev-kit/blob/54e537e6660e3c59eb6dfcaac74bc897486d3466/config/dev-kit.yml#L49-L58

In my opinion this just increases cognitive load and does not bring any value, I would rather use them in the `projects.yaml`
```diff
doctrine-mongodb-admin-bundle:
  branches:
    master:
      php: ['7.2', '7.3', '7.4']
      services: [mongodb]
      versions:
-        symfony: ['4.4']
+        symfony/symfony: ['4.4']
-        sonata_admin: ['3']
+        sonata-project/admin-bundle: ['3']
```

and validate the vendor name with a regex, matching `vendor/package`.

WDYT?

@greg0ire maybe you can remember, why we did this mapping in the past?

**Comment by greg0ire** [comment]
That was introduced in #67, let's see if there is a comment on that.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/dev-kit/pull/67/files#r481786080

**Comment by OskarStark** [comment]
Yes it was used to have proper env variables like `$SYMFONY`, but this was only need on Travis, we don't need it anymore with GithubActions

**Comment by greg0ire** [comment]
Great then, we can safely get rid of them then.

**Comment by OskarStark** [comment]
Will provide a PR 👍

**Comment by OskarStark** [comment]
Which one do you prefer?
```yaml
  branches:
    master:
      php: ['7.3', '7.4']
      variants:
        - { package: 'symfony/symfony', version: '4.4' }
        - { package: 'sonata-project/block-bundle', version: '4' }
    3.x:
      php: ['7.2', '7.3', '7.4']
      variants:
        - package: 'symfony/symfony'
          version: '4.4'
        - package: 'sonata-project/block-bundle'
          version: '3'
```

or more simple like:
```yaml
Which one do you prefer?
```yaml
  branches:
    master:
      php: ['7.3', '7.4']
      variants:
        - 'symfony/symfony:4.4'
        - 'sonata-project/block-bundle:4'
```

**Comment by OskarStark** [comment]
I prefer the last one

**Comment by greg0ire** [comment]
How about this?

```yaml
  branches:
    master:
      php: ['7.3', '7.4']
      variants:
        'symfony/symfony': '4.4'
        'sonata-project/block-bundle': '4'
```

**Comment by OskarStark** [comment]
This is better, otherwise we cannot test more than one version of the same package:

```yaml
  branches:
    master:
      php: ['7.3', '7.4']
      variants:
        'symfony/symfony': ['4.4']
        'sonata-project/block-bundle': ['4']
```
